sudo: required
services: docker
language: generic
env:
  - DOCKER_FILE="Dockerfile.debian:10.py3" PYTHON="python3"
  - DOCKER_FILE="Dockerfile.debian:testing.py3" PYTHON="python3"
  - DOCKER_FILE="Dockerfile.ubuntu:rolling.py3" PYTHON="python3"

before_install:
  - docker build -t nete -f "$DOCKER_FILE" .

before_script:
  - docker run --volume "$(pwd):/app" --workdir "/app" --tty --detach nete bash > container_id

script:
  - docker exec -e TRAVIS=true "$(cat container_id)" "$PYTHON" setup.py install
  - docker exec -e TRAVIS=true "$(cat container_id)" xvfb-run pytest-3 -s
  - docker exec -e TRAVIS=true "$(cat container_id)" "$PYTHON" -m pycodestyle nete

after_script:
  - docker stop "$(cat container_id)"
