SELECT_NOTE = 'SELECT_NOTE'
CREATE_NOTE = 'CREATE_NOTE'

TOGGLE_EDIT_NOTE_TEXT = 'TOGGLE_EDIT_NOTE_TEXT'
CHANGE_NOTE_TEXT = 'CHANGE_NOTE_TEXT'
FINISH_EDIT_NOTE_TEXT = 'FINISH_EDIT_NOTE_TEXT'

TOGGLE_EDIT_NOTE_TITLE = 'TOGGLE_EDIT_NOTE_TITLE'
CHANGE_NOTE_TITLE = 'CHANGE_NOTE_TITLE'
FINISH_EDIT_NOTE_TITLE = 'FINISH_EDIT_NOTE_TITLE'

LOADED_NOTES = 'LOADED_NOTES'
LOADED_UI_STATE = 'LOADED_UI_STATE'

SELECT_FIRST = 'SELECT_FIRST'
SELECT_NEXT = 'SELECT_NEXT'
SELECT_PREVIOUS = 'SELECT_PREVIOUS'

MOVE_OR_RESIZE_WINDOW = 'MOVE_OR_RESIZE_WINDOW'
