SELECT_NOTE = 'SELECT_NOTE'

TOGGLE_EDIT_NOTE_TEXT = 'TOGGLE_EDIT_NOTE_TEXT'
CHANGE_NOTE_TEXT = 'CHANGE_NOTE_TEXT'
FINISH_EDIT_NOTE_TEXT = 'FINISH_EDIT_NOTE_TEXT'

TOGGLE_EDIT_NOTE_TITLE = 'TOGGLE_EDIT_NOTE_TITLE'
CHANGE_NOTE_TITLE = 'CHANGE_NOTE_TITLE'
FINISH_EDIT_NOTE_TITLE = 'FINISH_EDIT_NOTE_TITLE'

LOADED_NOTES = 'LOADED_NOTES'

NEXT_NOTE = 'NEXT_NOTE'
PREV_NOTE = 'PREV_NOTE'
